#!/usr/bin/env python3
"""Create and check the local runner's identity.

The identity is generated by Custos, inside the Custos image, because the paths
it records are paths inside the container. Generating it on the host would record
a machine credential path the runner cannot find, and the failure would read as a
missing vault. This module decides when to ask for one, and afterwards checks that
what came back is what the runner will accept: the document's fields and the
machine credential it names, since the runner loads both before anything else.

A locally generated identity is unattested and refused for live trading.

Usage:
    python3 tools/runner/identity.py init --tenant-id local --image IMAGE
    python3 tools/runner/identity.py check --tenant-id local
    python3 tools/runner/identity.py check-vault --credential-id binance-my_idea-sandbox
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tomllib
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools import ui  # noqa: E402

ARX_ROOT = ROOT / ".runner" / ".arx"
CONTAINER_ARX_ROOT = PurePosixPath("/home/custos/.arx")
CONTAINER_RUNNER_TOML = CONTAINER_ARX_ROOT / "runner.toml"
CONTAINER_MACHINE_VAULT = CONTAINER_ARX_ROOT / "vault" / "runner-machine.enc"

# The runner treats an unexpected key as fatally as a missing one, so this does too.
RUNNER_FIELDS = {
    "tenant_id",
    "runner_id",
    "backend_url",
    "credential_id",
    "credential_version",
    "credential_valid_until",
    "machine_key_id",
    "machine_vault_path",
    "enrolled_at",
}


class IdentityError(ValueError):
    pass


def _require_mode(path: Path, expected: int) -> None:
    actual = path.stat().st_mode & 0o777
    if actual != expected:
        raise IdentityError(f"{path} must have mode {oct(expected)}, found {oct(actual)}")


def ensure_root() -> None:
    ARX_ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(ARX_ROOT, 0o700)


def read_runner_toml() -> dict:
    path = ARX_ROOT / "runner.toml"
    if not path.is_file():
        raise IdentityError(f"{path} is missing; run `make runner-init` once")
    _require_mode(path, 0o600)
    with path.open("rb") as handle:
        data = tomllib.load(handle)
    missing = sorted(RUNNER_FIELDS - set(data))
    unexpected = sorted(set(data) - RUNNER_FIELDS)
    if missing or unexpected:
        detail = "; ".join(
            part
            for part in (
                f"missing {', '.join(missing)}" if missing else "",
                f"unexpected {', '.join(unexpected)}" if unexpected else "",
            )
            if part
        )
        raise IdentityError(f"{path} is not a runner identity the image accepts ({detail})")
    version = data["credential_version"]
    if isinstance(version, bool) or not isinstance(version, int) or version < 1:
        raise IdentityError("runner.toml credential_version must be a positive integer")
    return data


def check_identity(tenant_id: str | None) -> None:
    ensure_root()
    data = read_runner_toml()
    if tenant_id is not None and data["tenant_id"] != tenant_id:
        raise IdentityError(
            f"the identity belongs to tenant {data['tenant_id']!r}, not {tenant_id!r}"
        )
    try:
        relative = PurePosixPath(str(data["machine_vault_path"])).relative_to(CONTAINER_ARX_ROOT)
    except ValueError:
        raise IdentityError(
            "runner.toml records a machine credential outside the container's "
            f"{CONTAINER_ARX_ROOT}; generate the identity with `make runner-init`"
        ) from None
    machine_vault = ARX_ROOT.joinpath(*relative.parts)
    if not machine_vault.is_file():
        raise IdentityError(f"{machine_vault} is missing; the runner loads it before anything else")
    _require_mode(machine_vault, 0o600)


def check_vault(credential_id: str) -> None:
    check_identity(None)
    age_key = ARX_ROOT / "age.key"
    if not age_key.is_file():
        raise IdentityError(f"{age_key} is missing; run `make runner-init` once")
    _require_mode(age_key, 0o600)
    credential = ARX_ROOT / "vault" / f"{credential_id}.enc"
    if not credential.is_file():
        raise IdentityError(
            f"{credential} is missing; store the exchange key with `make runner-vault`"
        )
    _require_mode(credential, 0o600)


def age_recipient() -> str:
    script = Path(__file__).resolve().parent / "age_key.sh"
    result = subprocess.run(
        ["bash", str(script), str(ARX_ROOT)], check=True, capture_output=True, text=True
    )
    recipient = result.stdout.strip()
    if not recipient.startswith("age1"):
        raise IdentityError(f"age_key.sh returned no age recipient: {recipient!r}")
    return recipient


def init(tenant_id: str, image: str) -> None:
    ensure_root()
    existing = [
        path
        for path in (ARX_ROOT / "runner.toml", ARX_ROOT / "vault" / "runner-machine.enc")
        if path.exists()
    ]
    if existing:
        names = ", ".join(str(path.relative_to(ROOT)) for path in existing)
        raise IdentityError(
            f"an identity already exists ({names}); the document and the machine credential "
            "are bound to each other, so remove both on purpose before generating another"
        )
    subprocess.run(
        [
            "docker", "run", "--rm",
            "-v", f"{ARX_ROOT}:{CONTAINER_ARX_ROOT}",
            image,
            "identity", "standalone",
            "--tenant-id", tenant_id,
            "--age-recipient", age_recipient(),
            "--runner-toml", str(CONTAINER_RUNNER_TOML),
            "--machine-vault", str(CONTAINER_MACHINE_VAULT),
        ],
        check=True,
    )  # fmt: skip
    check_identity(tenant_id)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    init_parser = commands.add_parser("init")
    init_parser.add_argument("--tenant-id", required=True)
    init_parser.add_argument("--image", required=True)
    check_parser = commands.add_parser("check")
    check_parser.add_argument("--tenant-id", required=True)
    vault_parser = commands.add_parser("check-vault")
    vault_parser.add_argument("--credential-id", required=True)
    args = parser.parse_args(argv[1:])
    try:
        if args.command == "init":
            init(args.tenant_id, args.image)
            ui.ok("this machine's runner identity is created")
        elif args.command == "check":
            check_identity(args.tenant_id)
            ui.ok("runner identity is in place")
        else:
            check_vault(args.credential_id)
            ui.ok("the key is sealed")
    except IdentityError as error:
        ui.error(str(error))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
