"""Reading a signed release back from its package, as ARX needs it.

Every release here is generated by the test: the layers, the two manifests and
the publication receipt are built the way the strategy publisher builds them,
with real SHA-256 digests. A fake registry serves them by digest; nothing is
recorded from a real registry.
"""

from __future__ import annotations

import base64
import copy
import hashlib
import json
import subprocess
import uuid
from collections.abc import Sequence
from pathlib import Path
from urllib import parse

import pytest

from tools.arx import evidence
from tools.arx.client import ArxError, Response

REPOSITORY = "ghcr.io/fork-owner/strategies/strategy-releases"
OCI_MANIFEST = "application/vnd.oci.image.manifest.v1+json"
ROLE = "dev.alephain.layer.role"
TITLE = "org.opencontainers.image.title"
MEDIA = {
    "release_config": "application/vnd.alephain.strategy-release.config.v1+json",
    "strategy_artifact": "application/vnd.alephain.strategy-wheel.v1+zip",
    "strategy_manifest": "application/vnd.alephain.strategy-manifest.v1+json",
    "strategy_artifact_ref": "application/vnd.alephain.strategy-artifact-ref.v1+json",
    "strategy_release_bom": "application/vnd.alephain.strategy-release-bom.v1+json",
    "strategy_sbom": "application/spdx+json",
    "strategy_release_statement": "application/vnd.in-toto+json",
    "attestation_config": "application/vnd.alephain.strategy-release.attestation.config.v1+json",
    "attestation_bundle": "application/vnd.dev.sigstore.bundle.v0.3+json",
    "artifact_attestation_ref": "application/vnd.alephain.artifact-attestation-ref.v1+json",
}


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def sha(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def entry(role: str, name: str, content: bytes) -> dict:
    return {
        "digest": f"sha256:{sha(content)}",
        "media_type": MEDIA[role],
        "name": name,
        "role": role,
        "size_bytes": len(content),
    }


def manifest_descriptor(item: dict, annotated: bool) -> dict:
    value = {"digest": item["digest"], "mediaType": item["media_type"], "size": item["size_bytes"]}
    if annotated:
        value["annotations"] = {ROLE: item["role"], TITLE: item["name"]}
    return value


class Release:
    """One published release: its blobs and manifests by digest, and its receipt."""

    def __init__(self) -> None:
        self.manifests: dict[str, bytes] = {}
        self.blobs: dict[str, bytes] = {}
        statement = canonical(
            {
                "_type": "https://in-toto.io/Statement/v1",
                "subject": [{"name": "strategy.whl", "digest": {"sha256": "ab" * 32}}],
                "predicateType": "https://example.com/strategy-release/v1",
                "predicate": {"version": "0.2.0"},
            }
        )
        bundle = canonical({"mediaType": MEDIA["attestation_bundle"], "signature": "c2ln"})
        layers = [
            ("release_config", "strategy-release-oci-config-v1.json", canonical({"k": "v"})),
            ("strategy_artifact", "strategy.whl", b"PK\x03\x04 wheel bytes"),
            (
                "strategy_manifest",
                "strategy-manifest.json",
                canonical(
                    {
                        "name": "trend/my_idea",
                        "trading_scope": {
                            "connector": "binance",
                            "pairs": ["BTC-USDT"],
                            "leverage": 1,
                        },
                        "note": "ünïcode stays as written",
                    }
                ),
            ),
            ("strategy_artifact_ref", "strategy-artifact-ref.json", canonical({"ref": "wheel"})),
            ("strategy_release_bom", "strategy-release-bom.json", canonical({"bom": 1})),
            ("strategy_sbom", "strategy.spdx.json", canonical({"spdxVersion": "SPDX-2.3"})),
            ("strategy_release_statement", "strategy-release-statement.json", statement),
        ]
        release_matrix = [entry(role, name, content) for role, name, content in layers]
        for (_, _, content), item in zip(layers, release_matrix, strict=True):
            self.blobs[item["digest"]] = content
        release_manifest = canonical(
            {
                "artifactType": "application/vnd.alephain.strategy-release.v1",
                "config": manifest_descriptor(release_matrix[0], annotated=False),
                "layers": [
                    manifest_descriptor(item, annotated=True) for item in release_matrix[1:]
                ],
                "mediaType": OCI_MANIFEST,
                "schemaVersion": 2,
            }
        )
        release_digest = f"sha256:{sha(release_manifest)}"
        self.manifests[release_digest] = release_manifest
        attestation_ref = canonical(
            {
                "bundle_coordinate": f"{REPOSITORY}@sha256:{sha(bundle)}",
                "bundle_sha256": sha(bundle),
                "payload_type": "application/vnd.in-toto+json",
                "predicate_type": "https://example.com/strategy-release/v1",
                "schema_version": "alephain.artifact-attestation-ref.v1",
                "statement_coordinate": f"{REPOSITORY}@sha256:{sha(statement)}",
                "statement_sha256": sha(statement),
            }
        )
        attestation_layers = [
            ("attestation_config", "attestation-config.json", canonical({"a": 1})),
            ("attestation_bundle", "strategy-release.sigstore.json", bundle),
            ("artifact_attestation_ref", "artifact-attestation-ref.json", attestation_ref),
        ]
        attestation_matrix = [entry(r, n, c) for r, n, c in attestation_layers]
        for (_, _, content), item in zip(attestation_layers, attestation_matrix, strict=True):
            self.blobs[item["digest"]] = content
        self.subject = {
            "digest": release_digest,
            "mediaType": OCI_MANIFEST,
            "size": len(release_manifest),
        }
        self.attestation_matrix = attestation_matrix
        self._write_attestation_manifest()
        artifact_ref = {
            "artifact_kind": "oci",
            "artifact_type": "application/vnd.alephain.strategy-release.v1",
            "config": {k: release_matrix[0][k] for k in ("digest", "media_type", "size_bytes")},
            "layers": release_matrix[1:],
            "manifest_digest": release_digest,
            "registry": "ghcr.io",
            "repository": REPOSITORY.removeprefix("ghcr.io/"),
            "schema_version": 1,
        }
        self.receipt = {
            "artifact_ref": artifact_ref,
            "artifact_ref_digest": sha(canonical(artifact_ref)),
            "attestation_descriptor_matrix": attestation_matrix,
            "attestation_descriptor_matrix_digest": sha(canonical(attestation_matrix)),
            "attestation_manifest_digest": self.attestation_digest,
            "attestation_manifest_size_bytes": len(self.manifests[self.attestation_digest]),
            "blob_readback_verified": True,
            "discovery_tag": "trend-my_idea-0.2.0",
            "external_publication_completed": False,
            "manifest_readback_verified": True,
            "producer_commit": "a" * 40,
            "producer_repository": "fork-owner/strategies",
            "publisher_profile": "github_oidc",
            "referrer_verified": True,
            "release_descriptor_matrix": release_matrix,
            "release_descriptor_matrix_digest": sha(canonical(release_matrix)),
            "release_manifest_digest": release_digest,
            "release_manifest_size_bytes": len(release_manifest),
            "repository": REPOSITORY,
            "schema_version": "alephain.strategy-artifact-oci-publication-receipt.v1",
            "strategy_coordinate": "trend/my_idea",
            "tag_is_authority": False,
            "workflow": {"workflow_ref": "o/r/.github/workflows/w.yml@refs/tags/v1"},
        }

    def _write_attestation_manifest(self) -> None:
        matrix = self.attestation_matrix
        content = canonical(
            {
                "artifactType": "application/vnd.alephain.strategy-release.attestation.v1",
                "config": manifest_descriptor(matrix[0], annotated=False),
                "layers": [manifest_descriptor(item, annotated=True) for item in matrix[1:]],
                "mediaType": OCI_MANIFEST,
                "schemaVersion": 2,
                "subject": self.subject,
            }
        )
        self.attestation_digest = f"sha256:{sha(content)}"
        self.manifests[self.attestation_digest] = content

    def layer(self, role: str) -> bytes:
        matrix = self.receipt["release_descriptor_matrix"] + self.attestation_matrix
        return self.blobs[next(item["digest"] for item in matrix if item["role"] == role)]

    def save(self, root: Path, version: str = "0.2.0") -> Path:
        run = root / ".releases" / "trend" / "my_idea" / version / "strategy-release-receipt-7-1"
        run.mkdir(parents=True, exist_ok=True)
        path = run / evidence.RECEIPT_FILE
        path.write_bytes(canonical(self.receipt))
        return path


class FakeRegistry:
    """Serves what a Release published, by digest; records what it was asked."""

    def __init__(self, release: Release) -> None:
        self.release = release
        self.asked: list[str] = []

    def manifest(self, digest: str) -> bytes:
        self.asked.append(digest)
        return self.release.manifests[digest]

    def blob(self, digest: str) -> bytes:
        self.asked.append(digest)
        return self.release.blobs[digest]


@pytest.fixture
def release() -> Release:
    return Release()


RELEASE_ID = "8b2e4c1a-5d3f-4e7a-9c06-1f2a3b4c5d6e"


def _read(release: Release, tmp_path: Path, receipt: dict | None = None):
    if receipt is not None:
        release.receipt = receipt
    path = release.save(tmp_path)
    return evidence.read_release(
        evidence.load_receipt(path, version="0.2.0"), FakeRegistry(release), receipt_path=path
    )


# What ARX gets


def test_a_published_release_becomes_the_evidence_arx_drafts_from(release, tmp_path) -> None:
    found = _read(release, tmp_path)
    drafted = found.artifact_evidence(RELEASE_ID)

    assert len(drafted) == 15
    assert drafted["strategy_release_id"] == RELEASE_ID
    manifest = release.layer("strategy_manifest")
    assert drafted["manifest_canonical_json"] == manifest.decode("utf-8")
    assert drafted["manifest"] == json.loads(manifest)
    assert drafted["manifest_digest"] == sha(manifest)
    for field, role in (
        ("artifact_ref", "strategy_artifact_ref"),
        ("release_bom", "strategy_release_bom"),
        ("release_statement", "strategy_release_statement"),
        ("detached_attestation_ref", "artifact_attestation_ref"),
    ):
        content = release.layer(role)
        assert drafted[f"{field}_canonical_json"] == content.decode("utf-8")
        assert drafted[f"{field}_digest"] == sha(content)
        assert len(drafted[f"{field}_digest"]) == 64
    assert drafted["release_statement"] == json.loads(release.layer("strategy_release_statement"))
    assert drafted["artifact_ref"] == json.loads(release.layer("strategy_artifact_ref"))
    assert "release_bom" not in drafted
    assert base64.b64decode(found.attestation_bundle_base64) == release.layer("attestation_bundle")
    assert found.trading_scope == {"connector": "binance", "pairs": ["BTC-USDT"], "leverage": 1}


def test_every_descriptor_of_both_manifests_is_read_by_digest(release, tmp_path) -> None:
    path = release.save(tmp_path)
    registry = FakeRegistry(release)

    evidence.read_release(evidence.load_receipt(path), registry, receipt_path=path)

    matrix = release.receipt["release_descriptor_matrix"] + release.attestation_matrix
    assert set(registry.asked) == {item["digest"] for item in matrix} | {
        release.receipt["release_manifest_digest"],
        release.receipt["attestation_manifest_digest"],
    }


@pytest.mark.parametrize("bad", [str(uuid.UUID(int=0)), "not-a-uuid"])
def test_the_release_id_must_be_a_non_nil_uuid(release, tmp_path, bad) -> None:
    with pytest.raises(ArxError):
        _read(release, tmp_path).artifact_evidence(bad)


# What the registry serves must be what the receipt names


def test_a_blob_whose_bytes_differ_is_refused(release, tmp_path) -> None:
    digest = next(
        item["digest"]
        for item in release.receipt["release_descriptor_matrix"]
        if item["role"] == "strategy_manifest"
    )
    release.blobs[digest] = release.blobs[digest].replace(b"BTC", b"ETH")

    with pytest.raises(ArxError, match="strategy_manifest.*digest"):
        _read(release, tmp_path)


def test_a_blob_of_another_size_is_refused(release, tmp_path) -> None:
    receipt = copy.deepcopy(release.receipt)
    # The receipt and both matrices agree on a size the registry's bytes do not have.
    for matrix in (receipt["release_descriptor_matrix"], receipt["artifact_ref"]["layers"]):
        for item in matrix:
            if item["role"] == "strategy_release_bom":
                item["size_bytes"] += 1
    _resign(receipt)

    with pytest.raises(ArxError, match="size"):
        _read(release, tmp_path, receipt)


def test_a_manifest_whose_bytes_differ_is_refused(release, tmp_path) -> None:
    digest = release.receipt["release_manifest_digest"]
    release.manifests[digest] = release.manifests[digest] + b" "

    with pytest.raises(ArxError, match="release manifest"):
        _read(release, tmp_path)


def test_an_attestation_whose_subject_is_another_release_is_refused(release, tmp_path) -> None:
    release.subject = dict(release.subject, digest=f"sha256:{'0' * 64}")
    release._write_attestation_manifest()
    receipt = copy.deepcopy(release.receipt)
    receipt["attestation_manifest_digest"] = release.attestation_digest
    receipt["attestation_manifest_size_bytes"] = len(release.manifests[release.attestation_digest])

    with pytest.raises(ArxError, match="subject"):
        _read(release, tmp_path, receipt)


def test_an_attestation_without_a_subject_is_refused(release, tmp_path) -> None:
    release.subject = None
    release._write_attestation_manifest()
    receipt = copy.deepcopy(release.receipt)
    receipt["attestation_manifest_digest"] = release.attestation_digest
    receipt["attestation_manifest_size_bytes"] = len(release.manifests[release.attestation_digest])

    with pytest.raises(ArxError, match="subject"):
        _read(release, tmp_path, receipt)


def test_a_manifest_layer_the_receipt_does_not_list_is_refused(release, tmp_path) -> None:
    digest = release.receipt["release_manifest_digest"]
    document = json.loads(release.manifests.pop(digest))
    document["layers"][0]["annotations"][TITLE] = "renamed.whl"
    content = canonical(document)
    new_digest = f"sha256:{sha(content)}"
    release.manifests[new_digest] = content
    receipt = copy.deepcopy(release.receipt)
    receipt["release_manifest_digest"] = new_digest
    receipt["release_manifest_size_bytes"] = len(content)
    receipt["artifact_ref"]["manifest_digest"] = new_digest
    _resign(receipt)

    with pytest.raises(ArxError, match="release manifest.*layer"):
        _read(release, tmp_path, receipt)


# The receipt must agree with itself


def _resign(receipt: dict) -> None:
    """Recompute the receipt's own digests, as a forger would."""
    receipt["artifact_ref_digest"] = sha(canonical(receipt["artifact_ref"]))
    receipt["release_descriptor_matrix_digest"] = sha(
        canonical(receipt["release_descriptor_matrix"])
    )
    receipt["attestation_descriptor_matrix_digest"] = sha(
        canonical(receipt["attestation_descriptor_matrix"])
    )


@pytest.mark.parametrize(
    ("change", "complaint"),
    [
        (lambda r: r.update(release_descriptor_matrix_digest="0" * 64), "matrix"),
        (lambda r: r.update(attestation_descriptor_matrix_digest="0" * 64), "matrix"),
        (lambda r: r.update(artifact_ref_digest="0" * 64), "artifact_ref"),
        (lambda r: r["artifact_ref"].update(manifest_digest=f"sha256:{'1' * 64}"), "artifact_ref"),
        (lambda r: r.update(schema_version="something.else.v2"), "schema"),
        (lambda r: r.update(tag_is_authority=True), "tag"),
        (lambda r: r.update(referrer_verified=False), "verified"),
        (lambda r: r.update(repository="docker.io/someone/strategies"), "ghcr.io"),
        (lambda r: r.update(release_manifest_digest="sha256:short"), "digest"),
        (lambda r: r.update(discovery_tag="trend-my_idea-0.3.0"), "0.2.0"),
        (lambda r: r.pop("workflow"), "workflow"),
        (lambda r: r.update(extra=1), "extra"),
    ],
)
def test_a_receipt_that_disagrees_with_itself_is_refused(
    release, tmp_path, change, complaint
) -> None:
    receipt = copy.deepcopy(release.receipt)
    change(receipt)

    with pytest.raises(ArxError, match=complaint):
        _read(release, tmp_path, receipt)


def test_a_receipt_with_its_layers_out_of_order_is_refused_even_if_resigned(
    release, tmp_path
) -> None:
    receipt = copy.deepcopy(release.receipt)
    matrix = receipt["release_descriptor_matrix"]
    matrix[1], matrix[2] = matrix[2], matrix[1]
    receipt["artifact_ref"]["layers"] = matrix[1:]
    _resign(receipt)

    with pytest.raises(ArxError, match="order"):
        _read(release, tmp_path, receipt)


def test_a_receipt_whose_artifact_ref_names_other_layers_is_refused(release, tmp_path) -> None:
    receipt = copy.deepcopy(release.receipt)
    receipt["artifact_ref"]["layers"][0] = dict(
        receipt["artifact_ref"]["layers"][0], digest=f"sha256:{'2' * 64}"
    )
    _resign(receipt)

    with pytest.raises(ArxError, match="artifact_ref"):
        _read(release, tmp_path, receipt)


def test_an_attestation_ref_for_another_statement_is_refused(release, tmp_path) -> None:
    digest = next(
        i["digest"] for i in release.attestation_matrix if i["role"] == "artifact_attestation_ref"
    )
    document = json.loads(release.blobs[digest])
    document["statement_sha256"] = "3" * 64
    content = canonical(document)
    del release.blobs[digest]
    item = next(i for i in release.attestation_matrix if i["role"] == "artifact_attestation_ref")
    item.update(digest=f"sha256:{sha(content)}", size_bytes=len(content))
    release.blobs[item["digest"]] = content
    release._write_attestation_manifest()
    receipt = copy.deepcopy(release.receipt)
    receipt["attestation_descriptor_matrix"] = release.attestation_matrix
    receipt["attestation_manifest_digest"] = release.attestation_digest
    receipt["attestation_manifest_size_bytes"] = len(release.manifests[release.attestation_digest])
    _resign(receipt)

    with pytest.raises(ArxError, match="statement"):
        _read(release, tmp_path, receipt)


# Finding the receipt


def test_the_receipt_is_found_under_the_strategy_and_version(release, tmp_path) -> None:
    path = release.save(tmp_path)

    assert evidence.find_receipt(tmp_path, "trend/my_idea", "0.2.0") == path
    with pytest.raises(ArxError, match="0.3.0") as missing:
        evidence.find_receipt(tmp_path, "trend/my_idea", "0.3.0")
    assert missing.value.fix == "make release STRATEGY=trend/my_idea"


# Reading from GHCR


class FakeGhcr:
    """GHCR's token exchange and its /v2 reads, over the transport interface."""

    def __init__(self, release: Release, *, token_status: int = 200) -> None:
        self.release = release
        self.token_status = token_status
        self.calls: list[tuple[str, str, dict]] = []

    def __call__(self, method: str, url: str, headers, body) -> Response:
        self.calls.append((method, url, dict(headers)))
        parts = parse.urlsplit(url)
        if parts.path == "/token":
            if self.token_status != 200:
                return Response(self.token_status, [], b'{"errors":[{"code":"DENIED"}]}')
            return Response(200, [], json.dumps({"token": "registry-bearer"}).encode())
        if headers.get("Authorization") != "Bearer registry-bearer":
            return Response(401, [], b"")
        name, kind, digest = parts.path.removeprefix("/v2/").rsplit("/", 2)
        if name != REPOSITORY.removeprefix("ghcr.io/"):
            return Response(404, [], b"")
        store = self.release.manifests if kind == "manifests" else self.release.blobs
        if digest not in store:
            return Response(404, [], b"")
        return Response(200, [("Docker-Content-Digest", digest)], store[digest])


def test_ghcr_is_asked_for_pull_on_the_one_repository_only(release, tmp_path) -> None:
    path = release.save(tmp_path)
    ghcr = FakeGhcr(release)
    reader = evidence.GhcrReader(REPOSITORY, "person", "gho_secret", transport=ghcr)

    evidence.read_release(evidence.load_receipt(path), reader, receipt_path=path)

    exchanges = [call for call in ghcr.calls if parse.urlsplit(call[1]).path == "/token"]
    assert len(exchanges) == 1
    query = parse.parse_qs(parse.urlsplit(exchanges[0][1]).query)
    assert query == {
        "scope": ["repository:fork-owner/strategies/strategy-releases:pull"],
        "service": ["ghcr.io"],
    }
    assert exchanges[0][2]["Authorization"].startswith("Basic ")
    for method, url, headers in ghcr.calls:
        assert method == "GET"
        assert "gho_secret" not in url
        if parse.urlsplit(url).path != "/token":
            assert headers["Authorization"] == "Bearer registry-bearer"


def test_a_reader_for_another_registry_is_refused() -> None:
    with pytest.raises(ArxError, match="ghcr.io"):
        evidence.GhcrReader("docker.io/someone/strategies", "person", "t", transport=None)


def test_a_denied_token_exchange_says_to_add_read_packages(release, tmp_path) -> None:
    path = release.save(tmp_path)
    reader = evidence.GhcrReader(
        REPOSITORY, "person", "gho_secret", transport=FakeGhcr(release, token_status=403)
    )

    with pytest.raises(ArxError) as refused:
        evidence.read_release(evidence.load_receipt(path), reader, receipt_path=path)

    assert refused.value.fix == "gh auth refresh -s read:packages"
    assert "gho_secret" not in str(refused.value)


# GitHub credentials


class FakeGhCli:
    def __init__(self, scopes: str | None, logged_in: bool = True) -> None:
        self.scopes = scopes
        self.logged_in = logged_in
        self.calls: list[list[str]] = []

    def __call__(self, command: Sequence[str]) -> subprocess.CompletedProcess[str]:
        command = list(command)
        self.calls.append(command)
        if not self.logged_in:
            return subprocess.CompletedProcess(command, 1, "", "not logged in")
        if command[1:3] == ["auth", "status"]:
            lines = ["github.com", "  ✓ Logged in to github.com account person (keyring)"]
            if self.scopes is not None:
                lines.append(f"  - Token scopes: {self.scopes}")
            return subprocess.CompletedProcess(command, 0, "\n".join(lines), "")
        if command[1:3] == ["auth", "token"]:
            return subprocess.CompletedProcess(command, 0, "gho_secret\n", "")
        if command[1:3] == ["api", "user"]:
            return subprocess.CompletedProcess(command, 0, "person\n", "")
        return subprocess.CompletedProcess(command, 1, "", "unexpected")


def test_credentials_come_from_gh_and_never_from_argv() -> None:
    gh = FakeGhCli("'repo', 'workflow', 'read:packages'")

    assert evidence.github_credentials(run=gh) == ("person", "gho_secret")
    assert all("gho_secret" not in part for call in gh.calls for part in call)


@pytest.mark.parametrize("scopes", ["'repo', 'workflow'", "'gist', 'read:org'"])
def test_a_token_without_read_packages_is_refused_with_the_fix(scopes: str) -> None:
    with pytest.raises(ArxError, match="read:packages") as refused:
        evidence.github_credentials(run=FakeGhCli(scopes))
    assert refused.value.fix == "gh auth refresh -s read:packages"


def test_write_packages_includes_reading_them() -> None:
    assert evidence.github_credentials(run=FakeGhCli("'repo', 'write:packages'"))[1] == "gho_secret"


def test_a_token_whose_scopes_gh_cannot_list_is_tried() -> None:
    assert evidence.github_credentials(run=FakeGhCli(None))[1] == "gho_secret"


def test_gh_must_be_logged_in() -> None:
    with pytest.raises(ArxError, match="gh is not logged in") as refused:
        evidence.github_credentials(run=FakeGhCli("'repo'", logged_in=False))
    assert "gh auth login" in refused.value.fix


def test_a_dropped_connection_is_tried_once_more(release, tmp_path) -> None:
    path = release.save(tmp_path)
    ghcr = FakeGhcr(release)
    dropped: list[str] = []

    def flaky(method, url, headers, body):
        if not dropped:
            dropped.append(url)
            raise ArxError("cannot reach ghcr.io: connection reset")
        return ghcr(method, url, headers, body)

    reader = evidence.GhcrReader(REPOSITORY, "person", "gho_secret", transport=flaky)

    assert evidence.read_release(evidence.load_receipt(path), reader, receipt_path=path).layers
    assert len(dropped) == 1


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(cwd), *args], check=True, capture_output=True)


def test_a_worktree_without_releases_reads_the_receipt_of_its_main_checkout(
    release, tmp_path, monkeypatch
) -> None:
    main = tmp_path / "main"
    main.mkdir()
    _git(main, "init", "-q")
    _git(main, "-c", "user.name=t", "-c", "user.email=t@example.com", "commit", "-q",
         "--allow-empty", "-m", "start")  # fmt: skip
    worktree = tmp_path / "worktree"
    _git(main, "worktree", "add", "-q", str(worktree))
    path = release.save(main)
    said: list[str] = []
    monkeypatch.setattr(evidence.ui, "info", lambda message, **k: said.append(message))

    found = evidence.find_receipt(worktree, "trend/my_idea", "0.2.0")

    assert found.resolve() == path.resolve()
    (note,) = said
    assert "main checkout" in note and str(found) in note
    # Where the worktree has its own, that one is read, and nothing is said.
    own = release.save(worktree)
    said.clear()
    assert evidence.find_receipt(worktree, "trend/my_idea", "0.2.0") == own
    assert said == []


def test_a_receipt_in_neither_checkout_is_refused_naming_both(release, tmp_path) -> None:
    main = tmp_path / "main"
    main.mkdir()
    _git(main, "init", "-q")
    _git(main, "-c", "user.name=t", "-c", "user.email=t@example.com", "commit", "-q",
         "--allow-empty", "-m", "start")  # fmt: skip
    worktree = tmp_path / "worktree"
    _git(main, "worktree", "add", "-q", str(worktree))

    with pytest.raises(ArxError) as missing:
        evidence.find_receipt(worktree, "trend/my_idea", "0.2.0")

    said = str(missing.value)
    assert str(worktree) in said and str(main.resolve()) in said
    assert missing.value.fix.startswith("make release STRATEGY=trend/my_idea")
